Update build-publish.yml

diff --git a/.github/workflows/build-publish.yml b/.github/workflows/build-publish.yml
--- a/.github/workflows/build-publish.yml
+++ b/.github/workflows/build-publish.yml
@@ -1,53 +1,57 @@
-name: "JFrog-GitHub NPM Publish OIDC Integration"
-on: push
+name: oidc-poc
 
-# This is required as per
-# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings
-permissions:
-  id-token: write
+on:
+    push:
+        branches:
+            - '*'
 
 jobs:
-  build:
-     runs-on: ubuntu-latest
-     env:
-      OIDC_AUDIENCE: 'jfrog-github'
-      OIDC_PROVIDER: 'github'
-      PLATFORM_REPO: 'eks-npm'
-     defaults:
-      run:
-        working-directory: ./package
-     steps:
-       - name: Checkout
-         uses: actions/checkout@v3
-              
-       - name: Setup Node npm
-         uses: actions/setup-node@v3
-   
-       - name: Setup JFrog CLI
-         uses: jfrog/setup-jfrog-cli@v3
-         env:  
-           JF_URL: ${{ secrets.JF_URL }}
-         with:
-           oidc-provider-name: ${{ env.OIDC_PROVIDER }}
-           oidc-audience: ${{ env.OIDC_AUDIENCE }}
+    auth:
+        permissions:
+            contents: read
+            id-token: write
+        runs-on: ubuntu-latest
+        steps:
+            - name: Get id token
+              run: |
+                    ID_TOKEN=$(curl -sLS -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
+                    "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=jfrog-github" | jq .value | tr -d '"')
+                    echo "ID_TOKEN=${ID_TOKEN}" >> $GITHUB_ENV
+                    echo "$ID_TOKEN"
+            
+            - name: Exchange token with access (Optional if you still need access token)
+              env:
+                    ID_TOKEN: ${{env.ID_TOKEN}}
+                    JFROG_PLATFORM_URL: https://hts2.jfrog.io
+              run: |
+                    EXCHANGE_RESPONSE=$(curl -XPOST -H "Content-Type: application/json" "https://hts2.jfrog.io/access/api/v1/oidc/token" -d \
+                    "{\"grant_type\": \"urn:ietf:params:oauth:grant-type:token-exchange\", \"subject_token_type\":\"urn:ietf:params:oauth:token-type:id_token\", \"subject_token\": \"${ID_TOKEN}\", \"provider_name\": \"github\"}")
+                    
+                    echo "Token Exchange Response: $EXCHANGE_RESPONSE"
+                    ACCESS_TOKEN=$(echo "$EXCHANGE_RESPONSE" | jq .access_token | tr -d '"')
+                    
+                    echo "Access Token: $ACCESS_TOKEN"
+                    
+                    if [ -z "$ACCESS_TOKEN" ]; then
+                      echo "Error: ACCESS_TOKEN is empty!"
+                      exit 1
+                    fi
+                    
+                    echo "ACCESS_TOKEN=${ACCESS_TOKEN}" >> $GITHUB_ENV
 
-       - name: Set CLI Config
-         run: jf npm-config --global=true --repo-resolve=$PLATFORM_REPO --repo-deploy=$PLATFORM_REPO
-           
-       - name: Install Dependencies
-         run: jf npm install
-           
-       - name: Run tests
-         run: npm test
-         
-       - name: Publish
-         run: jf npm publish
-         
-       - name: Publish Build info With JFrog CLI
-         run: |
-          # Collect environment variables for the build
-          jf rt build-collect-env
-          # Collect VCS details from git and add them to the build
-          jf rt build-add-git
-          # Publish build info
-          jf rt build-publish
+            - name: Install JFrog CLI
+              run: |
+                    curl -fL https://getcli.jfrog.io | sh
+                    sudo mv jfrog /usr/local/bin/
+
+            - name: Configure JFrog CLI with OIDC Token
+              env:
+                 ID_TOKEN: ${{ env.ID_TOKEN }}
+              run: |
+                    # Set the Artifactory URL and use OIDC token for authentication
+                    jfrog config add my-artifactory --url https://hts2.jfrog.io/artifactory --access-token $ID_TOKEN
+
+            - name: Ping Artifactory API with JFrog CLI (jf rt ping)
+              run: |
+                    echo "Pinging Artifactory using JFrog CLI..."
+                    jfrog rt ping --url https://hts2.jfrog.io/artifactory
